# Generated by Django 2.2.2 on 2019-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_auto_20190622_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='name',
            field=models.CharField(default='First', max_length=100),
            preserve_default=False,
        ),
    ]
