# Generated by Django 2.2.2 on 2019-06-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_objective_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='objectiveupdate',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
