# Generated by Django 2.2.2 on 2019-06-23 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0005_auto_20190623_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objective',
            name='members',
            field=models.ManyToManyField(blank=True, through='collab.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
