# Generated by Django 2.2.2 on 2019-06-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_auto_20190623_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('revision', models.IntegerField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Objective')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('revision', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='project',
        ),
        migrations.DeleteModel(
            name='ObjectiveUpdate',
        ),
        migrations.DeleteModel(
            name='ProjectUpdate',
        ),
    ]
