# Generated by Django 2.2.2 on 2019-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_auto_20190627_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivehistory',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
