# Generated by Django 2.2.2 on 2019-06-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_auto_20190627_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectivehistory',
            options={'ordering': ['-revision']},
        ),
    ]
