# Generated by Django 2.2.2 on 2019-06-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_auto_20190628_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthistory',
            options={'ordering': ['-revision']},
        ),
    ]
