# Generated by Django 2.2.2 on 2019-06-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_auto_20190628_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='public',
        ),
    ]
