# Generated by Django 2.2.2 on 2019-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_remove_project_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
