# Generated by Django 2.2.2 on 2019-07-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_auto_20190704_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
